
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/zoumo/logdog"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "github.com/caicloud/clientset"
  branch = "release-1.14"

[[override]]
  branch = "master"
  name = "github.com/mdlayher/raw"
 
[[override]]
  branch = "master"
  name = "github.com/mdlayher/arp"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v24.1.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v11.4.0"

[[constraint]]
  name = "github.com/zoumo/golib"
  revision = "60b6ea38fe1ce5cd8b1942e1cd6767d6fc3384d9^"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[[constraint]]
  name = "github.com/caicloud/go-common"
  version = "v0.2.6"

[[constraint]]
  name = "github.com/hanxueluo/go-bigip"
  branch = "release-11.x"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

